### ISSUE TITLE
The 'Load Leaf' option doesn't load the leaf files in correctly.

### ISSUE THREAD

**Issue by NinjaJayBird** [plasmawario/ThumperLevelEditor#23]
It does export! Windows can detect it if you try to delete the leaf file while the editor is open. But nothing changes in the UI so it doesn't export properly.

**Comment by plasmawario** [comment]
The "Load Leaf" option in the level file editor box is for selecting which leaf text files you want to add to your lvl text file, not for loading an actual leaf file, unfortunately! Sorry for the confusion!
